## BACKEND REQUEST TESTS:

### TOKEN (TEST ONLY)
#### Use actual returned authentication token
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6Imp1cmVAZ21haWwuY29tIiwiaWF0IjoxNzE2MzAwODA3LCJleHAiOjE3MTYzMDE3MDd9.jeuN6O24E7qbhoswuBNBvCvTCfl2DxyWb4QLYgwOSZk

### Register a new user
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Nick",
  "password": "nick123"
}

### Login user
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "name": "Nick",
  "password": "nick123"
}

## GET PLAYER
### POST /auth/register
GET http://localhost:3000/player/name/Nick2 HTTP/1.1
Content-Type: application/json

### GET GAMES
GET http://localhost:3000/game HTTP/1.1
Content-Type: application/json

## GET GAME
### POST /auth/register
GET http://localhost:3000/game/98 HTTP/1.1
Content-Type: application/json


## GET GAME TURN
### POST /auth/register
GET http://localhost:3000/game/46/turn HTTP/1.1
Content-Type: application/json

## CREATE GAME
### POST /auth/register
POST http://localhost:3000/game HTTP/1.1
Content-Type: application/json

{
  "id": 0,
  "decks": [
    {
      "id": 0,
      "size": 52,
      "cards": [
        {
          "id": 0,
          "priority": 1,
          "value": 1,
          "color": "B",
          "texture": "blue1"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 8,
          "color": "G",
          "texture": "green8"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 6,
          "color": "R",
          "texture": "red6"
        },
        {
          "id": 0,
          "priority": 4,
          "value": 20,
          "color": "G-Y",
          "texture": "plus2greenYellow"
        },
        {
          "id": 0,
          "priority": 6,
          "value": 50,
          "color": "-",
          "texture": "rainbow"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 1,
          "color": "Y",
          "texture": "yellow1"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 4,
          "color": "Y",
          "texture": "yellow4"
        },
        {
          "id": 0,
          "priority": 2,
          "value": 20,
          "color": "G",
          "texture": "stopGreen"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 3,
          "color": "R",
          "texture": "red3"
        },
        {
          "id": 0,
          "priority": 5,
          "value": 20,
          "color": "B",
          "texture": "plus2blue"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 6,
          "color": "B",
          "texture": "blue6"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 9,
          "color": "R",
          "texture": "red9"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 5,
          "color": "Y",
          "texture": "yellow5"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 6,
          "color": "G",
          "texture": "green6"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 1,
          "color": "G",
          "texture": "green1"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 9,
          "color": "B",
          "texture": "blue9"
        },
        {
          "id": 0,
          "priority": 5,
          "value": 20,
          "color": "G",
          "texture": "plus2green"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 5,
          "color": "R",
          "texture": "red5"
        },
        {
          "id": 0,
          "priority": 4,
          "value": 20,
          "color": "B-R",
          "texture": "plus2blueRed"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 9,
          "color": "G",
          "texture": "green9"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 2,
          "color": "Y",
          "texture": "yellow2"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 1,
          "color": "R",
          "texture": "red1"
        },
        {
          "id": 0,
          "priority": 3,
          "value": 20,
          "color": "R",
          "texture": "redReverse"
        },
        {
          "id": 0,
          "priority": 2,
          "value": 20,
          "color": "Y",
          "texture": "stopYellow"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 7,
          "color": "B",
          "texture": "blue7"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 6,
          "color": "Y",
          "texture": "yellow6"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 3,
          "color": "B",
          "texture": "blue3"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 5,
          "color": "G",
          "texture": "green5"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 4,
          "color": "B",
          "texture": "blue4"
        },
        {
          "id": 0,
          "priority": 3,
          "value": 20,
          "color": "B",
          "texture": "blueReverse"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 2,
          "color": "B",
          "texture": "blue2"
        },
        {
          "id": 0,
          "priority": 3,
          "value": 20,
          "color": "G",
          "texture": "greenReverse"
        },
        {
          "id": 0,
          "priority": 2,
          "value": 20,
          "color": "R",
          "texture": "stopRed"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 8,
          "color": "Y",
          "texture": "yellow8"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 8,
          "color": "R",
          "texture": "red8"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 7,
          "color": "Y",
          "texture": "yellow7"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 7,
          "color": "G",
          "texture": "green7"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 4,
          "color": "R",
          "texture": "red4"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 3,
          "color": "Y",
          "texture": "yellow3"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 3,
          "color": "G",
          "texture": "green3"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 2,
          "color": "R",
          "texture": "red2"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 4,
          "color": "G",
          "texture": "green4"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 7,
          "color": "R",
          "texture": "red7"
        },
        {
          "id": 0,
          "priority": 1,
          "value": 2,
          "color": "G",
          "texture": "green2"
        },
        {
          "id": 0,
          "priority": 5,
          "value": 20,
          "color": "R",
          "texture": "plus2red"
        },
        {
          "id": 0,
          "priority": 5,
          "value": 20,
          "color": "Y",
          "texture": "plus2yellow"
        },
        null,
        null,
        null
      ]
    },
    {
      "id": 0,
      "size": 52,
      "cards": [
        {
          "id": 0,
          "priority": 1,
          "value": 9,
          "color": "Y",
          "texture": "yellow9"
        },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    }
  ],
  "players": [
    {
      "id": 28,
      "name": "Nick1",
      "score": 0,
      "hand": {
        "id": 0,
        "indexFirst": 0,
        "indexLast": 4,
        "cards": [
          {
            "id": 0,
            "priority": 6,
            "value": 50,
            "color": "-",
            "texture": "plus4"
          },
          {
            "id": 0,
            "priority": 1,
            "value": 8,
            "color": "B",
            "texture": "blue8"
          },
          {
            "id": 0,
            "priority": 2,
            "value": 20,
            "color": "B",
            "texture": "stopBlue"
          },
          {
            "id": 0,
            "priority": 3,
            "value": 20,
            "color": "Y",
            "texture": "yellowReverse"
          },
          {
            "id": 0,
            "priority": 1,
            "value": 5,
            "color": "B",
            "texture": "blue5"
          },
          null
        ]
      }
    },
    null
  ],
  "maxPlayers": 2,
  "gameState": "Initializing",
  "currentTurn": 1,
  "turnOrder": "Clockwise"
}

## GET GAME PLAYERS
### POST /auth/register
GET http://localhost:3000/game/85/players HTTP/1.1
Content-Type: application/json

## ADD PLAYER TO GAME
### PUT /game/:id/players
PUT http://localhost:3000/game/85/players HTTP/1.1
Content-Type: application/json

{
  "id": 37,
  "name": "Nick2",
  "score": 0,
  "hand": {
    "id": 0,
    "indexFirst": 0,
    "indexLast": 4,
    "cards": [
      {
      "id": 5242,
      "handId": null,
      "priority": 1,
      "value": 4,
      "color": "G",
      "texture": "green4"
      },
      {
        "id": 5243,
        "handId": null,
        "priority": 1,
        "value": 7,
        "color": "R",
        "texture": "red7"
      },
      {
        "id": 5244,
        "handId": null,
        "priority": 1,
        "value": 2,
        "color": "G",
        "texture": "green2"
      },
      {
        "id": 5245,
        "handId": null,
        "priority": 5,
        "value": 20,
        "color": "R",
        "texture": "plus2red"
      },
      {
        "id": 5246,
        "handId": null,
        "priority": 5,
        "value": 20,
        "color": "Y",
        "texture": "plus2yellow"
      },
      null
    ]
  }
}

# REMOVE PLAYER FROM GAME
### PUT /game/:gameId/player/:playerId
PUT http://localhost:3000/game/96/player/28 HTTP/1.1
Content-Type: application/json

{
  "id": 28,
  "name": "Nick1",
  "score": 55,
  "hand": {
    "id": 81,
    "indexFirst": 0,
    "indexLast": 9,
    "cards": [
      {
        "id": 5788,
        "priority": 1,
        "value": 3,
        "color": "G",
        "texture": "green3"
      },
      {
        "id": 5796,
        "priority": 1,
        "value": 8,
        "color": "B",
        "texture": "blue8"
      },
      {
        "id": 5781,
        "priority": 1,
        "value": 6,
        "color": "B",
        "texture": "blue6"
      },
      {
        "id": 5782,
        "priority": 1,
        "value": 8,
        "color": "Y",
        "texture": "yellow8"
      },
      {
        "id": 5783,
        "priority": 1,
        "value": 5,
        "color": "Y",
        "texture": "yellow5"
      },
      {
        "id": 5779,
        "priority": 2,
        "value": 20,
        "color": "B",
        "texture": "stopBlue"
      },
      {
        "id": 5805,
        "priority": 3,
        "value": 20,
        "color": "B",
        "texture": "blueReverse"
      },
      {
        "id": 5778,
        "priority": 4,
        "value": 20,
        "color": "G-Y",
        "texture": "plus2greenYellow"
      },
      {
        "id": 5786,
        "priority": 2,
        "value": 20,
        "color": "G",
        "texture": "stopGreen"
      },
      {
        "id": 5784,
        "priority": 2,
        "value": 20,
        "color": "R",
        "texture": "stopRed"
      },
      {
        "id": 5775,
        "priority": 1,
        "value": 6,
        "color": "Y",
        "texture": "yellow6"
      },
      {
        "id": 5777,
        "priority": 1,
        "value": 4,
        "color": "B",
        "texture": "blue4"
      },
      {
        "id": 5773,
        "priority": 1,
        "value": 3,
        "color": "Y",
        "texture": "yellow3"
      },
      {
        "id": 5776,
        "priority": 1,
        "value": 2,
        "color": "G",
        "texture": "green2"
      },
      {
        "id": 5774,
        "priority": 1,
        "value": 4,
        "color": "R",
        "texture": "red4"
      },
      null
    ]
  }
}

## UPDATE GAME
### POST /auth/register
PUT http://localhost:3000/game/85 HTTP/1.1
Content-Type: application/json

{
  "id": 85,
  "decks": [
    {
      "id": 163,
      "gameId": 85,
      "size": 52,
      "cards": [
        {
          "id": 5201,
          "handId": null,
          "priority": 1,
          "value": 1,
          "color": "B",
          "texture": "blue1"
        },
        {
          "id": 5202,
          "handId": null,
          "priority": 1,
          "value": 8,
          "color": "G",
          "texture": "green8"
        },
        {
          "id": 5203,
          "handId": null,
          "priority": 1,
          "value": 6,
          "color": "R",
          "texture": "red6"
        },
        {
          "id": 5204,
          "handId": null,
          "priority": 4,
          "value": 20,
          "color": "G-Y",
          "texture": "plus2greenYellow"
        },
        {
          "id": 5205,
          "handId": null,
          "priority": 6,
          "value": 50,
          "color": "-",
          "texture": "rainbow"
        },
        {
          "id": 5206,
          "handId": null,
          "priority": 1,
          "value": 1,
          "color": "Y",
          "texture": "yellow1"
        },
        {
          "id": 5207,
          "handId": null,
          "priority": 1,
          "value": 4,
          "color": "Y",
          "texture": "yellow4"
        },
        {
          "id": 5208,
          "handId": null,
          "priority": 2,
          "value": 20,
          "color": "G",
          "texture": "stopGreen"
        },
        {
          "id": 5209,
          "handId": null,
          "priority": 1,
          "value": 3,
          "color": "R",
          "texture": "red3"
        },
        {
          "id": 5210,
          "handId": null,
          "priority": 5,
          "value": 20,
          "color": "B",
          "texture": "plus2blue"
        },
        {
          "id": 5211,
          "handId": null,
          "priority": 1,
          "value": 6,
          "color": "B",
          "texture": "blue6"
        },
        {
          "id": 5212,
          "handId": null,
          "priority": 1,
          "value": 9,
          "color": "R",
          "texture": "red9"
        },
        {
          "id": 5213,
          "handId": null,
          "priority": 1,
          "value": 5,
          "color": "Y",
          "texture": "yellow5"
        },
        {
          "id": 5214,
          "handId": null,
          "priority": 1,
          "value": 6,
          "color": "G",
          "texture": "green6"
        },
        {
          "id": 5215,
          "handId": null,
          "priority": 1,
          "value": 1,
          "color": "G",
          "texture": "green1"
        },
        {
          "id": 5216,
          "handId": null,
          "priority": 1,
          "value": 9,
          "color": "B",
          "texture": "blue9"
        },
        {
          "id": 5217,
          "handId": null,
          "priority": 5,
          "value": 20,
          "color": "G",
          "texture": "plus2green"
        },
        {
          "id": 5218,
          "handId": null,
          "priority": 1,
          "value": 5,
          "color": "R",
          "texture": "red5"
        },
        {
          "id": 5219,
          "handId": null,
          "priority": 4,
          "value": 20,
          "color": "B-R",
          "texture": "plus2blueRed"
        },
        {
          "id": 5220,
          "handId": null,
          "priority": 1,
          "value": 9,
          "color": "G",
          "texture": "green9"
        },
        {
          "id": 5221,
          "handId": null,
          "priority": 1,
          "value": 2,
          "color": "Y",
          "texture": "yellow2"
        },
        {
          "id": 5222,
          "handId": null,
          "priority": 1,
          "value": 1,
          "color": "R",
          "texture": "red1"
        },
        {
          "id": 5223,
          "handId": null,
          "priority": 3,
          "value": 20,
          "color": "R",
          "texture": "redReverse"
        },
        {
          "id": 5224,
          "handId": null,
          "priority": 2,
          "value": 20,
          "color": "Y",
          "texture": "stopYellow"
        },
        {
          "id": 5225,
          "handId": null,
          "priority": 1,
          "value": 7,
          "color": "B",
          "texture": "blue7"
        },
        {
          "id": 5226,
          "handId": null,
          "priority": 1,
          "value": 6,
          "color": "Y",
          "texture": "yellow6"
        },
        {
          "id": 5227,
          "handId": null,
          "priority": 1,
          "value": 3,
          "color": "B",
          "texture": "blue3"
        },
        {
          "id": 5228,
          "handId": null,
          "priority": 1,
          "value": 5,
          "color": "G",
          "texture": "green5"
        },
        {
          "id": 5229,
          "handId": null,
          "priority": 1,
          "value": 4,
          "color": "B",
          "texture": "blue4"
        },
        {
          "id": 5230,
          "handId": null,
          "priority": 3,
          "value": 20,
          "color": "B",
          "texture": "blueReverse"
        },
        {
          "id": 5231,
          "handId": null,
          "priority": 1,
          "value": 2,
          "color": "B",
          "texture": "blue2"
        },
        {
          "id": 5232,
          "handId": null,
          "priority": 3,
          "value": 20,
          "color": "G",
          "texture": "greenReverse"
        },
        {
          "id": 5233,
          "handId": null,
          "priority": 2,
          "value": 20,
          "color": "R",
          "texture": "stopRed"
        },
        {
          "id": 5234,
          "handId": null,
          "priority": 1,
          "value": 8,
          "color": "Y",
          "texture": "yellow8"
        },
        {
          "id": 5235,
          "handId": null,
          "priority": 1,
          "value": 8,
          "color": "R",
          "texture": "red8"
        },
        {
          "id": 5236,
          "handId": null,
          "priority": 1,
          "value": 7,
          "color": "Y",
          "texture": "yellow7"
        },
        {
          "id": 5237,
          "handId": null,
          "priority": 1,
          "value": 7,
          "color": "G",
          "texture": "green7"
        }
      ]
    },
    {
      "id": 164,
      "gameId": 85,
      "size": 52,
      "cards": [
        {
          "id": 5247,
          "handId": null,
          "priority": 1,
          "value": 9,
          "color": "Y",
          "texture": "yellow9"
        },
        {
          "id": 5248,
          "handId": 61,
          "priority": 6,
          "value": 50,
          "color": "-",
          "texture": "plus4"
        }
      ]
    }
  ],
  "players": [
    {
      "id": 28,
      "gameId": 85,
      "createdAt": "2024-08-11T12:46:04.607Z",
      "joinedAt": "2024-08-24T10:52:26.345Z",
      "name": "Nick1",
      "score": 0,
      "hand": {
        "id": 61,
        "playerId": 28,
        "indexFirst": 0,
        "indexLast": 4,
        "cards": [
          {
            "id": 5249,
            "handId": 61,
            "priority": 1,
            "value": 8,
            "color": "B",
            "texture": "blue8"
          },
          {
            "id": 5250,
            "handId": 61,
            "priority": 2,
            "value": 20,
            "color": "B",
            "texture": "stopBlue"
          },
          {
            "id": 5251,
            "handId": 61,
            "priority": 3,
            "value": 20,
            "color": "Y",
            "texture": "yellowReverse"
          },
          {
            "id": 5252,
            "handId": 61,
            "priority": 1,
            "value": 5,
            "color": "B",
            "texture": "blue5"
          }
        ]
      }
    },
    {
      "id": 37,
      "gameId": 85,
      "createdAt": "2024-08-12T15:23:53.234Z",
      "joinedAt": "2024-08-24T17:29:56.146Z",
      "name": "Nick2",
      "score": 0,
      "hand": {
        "id": 62,
        "playerId": 37,
        "indexFirst": 0,
        "indexLast": 4,
        "cards": [
          {
            "id": 5242,
            "handId": 62,
            "priority": 1,
            "value": 4,
            "color": "G",
            "texture": "green4"
          },
          {
            "id": 5243,
            "handId": 62,
            "priority": 1,
            "value": 7,
            "color": "R",
            "texture": "red7"
          },
          {
            "id": 5244,
            "handId": 62,
            "priority": 1,
            "value": 2,
            "color": "G",
            "texture": "green2"
          },
          {
            "id": 5245,
            "handId": 62,
            "priority": 5,
            "value": 20,
            "color": "R",
            "texture": "plus2red"
          },
          {
            "id": 5246,
            "handId": 62,
            "priority": 5,
            "value": 20,
            "color": "Y",
            "texture": "plus2yellow"
          },
          {
            "id": 5238,
            "handId": null,
            "priority": 1,
            "value": 4,
            "color": "R",
            "texture": "red4"
          },
          {
            "id": 5239,
            "handId": null,
            "priority": 1,
            "value": 3,
            "color": "Y",
            "texture": "yellow3"
          },
          {
            "id": 5240,
            "handId": null,
            "priority": 1,
            "value": 3,
            "color": "G",
            "texture": "green3"
          },
          {
            "id": 5241,
            "handId": null,
            "priority": 1,
            "value": 2,
            "color": "R",
            "texture": "red2"
          }
        ]
      }
    }
  ],
  "maxPlayers": 2,
  "gameState": "Running",
  "currentTurn": 2,
  "turnOrder": "Clockwise"
}


## GET DECK
### POST /auth/register
GET http://localhost:3000/deck/163 HTTP/1.1
Content-Type: application/json


## DELETE GAME
### POST /auth/register
DELETE http://localhost:3000/game/99 HTTP/1.1
Content-Type: application/json