-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "maxPlayers" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "topCardId" INTEGER;

-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_topCardId_fkey" FOREIGN KEY ("topCardId") REFERENCES "Card"("id") ON DELETE SET NULL ON UPDATE CASCADE;
